apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/react-wep-app:web-app-v19
        ports:
        - containerPort: 3000
