apiVersion: v1
kind: Service
metadata:
  name: gateway-external
  namespace: openfaas
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: gateway

