apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  creationTimestamp: "2023-04-19T14:30:11Z"
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-12.0.4
    component: gateway
    heritage: Helm
    release: openfaas
  name: gateway
  namespace: openfaas
  resourceVersion: "3399"
  uid: c2022570-c917-491b-8d21-a41bde70128c
spec:
  clusterIP: 10.100.42.4
  clusterIPs:
  - 10.100.42.4
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}