global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'openfaas-gateway'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['openfaas-gateway:8080']

  - job_name: 'openfaas-functions'
    metrics_path: '/metrics'
    scheme: 'http'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: 'gateway|function'
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: container_name
        regex: 'gateway|function'
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod_name
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace

