apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-05-01T17:04:54Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 103
  labels:
    app.kubernetes.io/managed-by: Helm
  name: openfaas
  namespace: argocd
  resourceVersion: "55171"
  uid: 931ac2b8-8d94-4614-80d0-b4afa0c4c3af
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        "account": "112172658395"
        "clusterName": "Terraform"
        "region": "eu-west-1"
        "repoUrl": "https://github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions.git"
    path: functions/charts/openfaas-functions/
    repoURL: https://github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions.git
    targetRevision: Svanfríður
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
      limit: 10
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
status:
  conditions:
  - lastTransitionTime: "2023-05-01T19:11:51Z"
    message: 'Failed sync attempt to 0e389d2b5fcfe70647ae9a0c51e24a40e62bcb8a: one
      or more objects failed to apply, reason: Service "demo-function" is invalid:
      spec.ports[0].name: Required value (retried 10 times).'
    type: SyncError
  health:
    status: Healthy
  history:
  - deployStartedAt: "2023-05-01T17:12:50Z"
    deployedAt: "2023-05-01T17:12:51Z"
    id: 0
    revision: 254b7b6161af27a0fa87ff38872c054d23f4bef2
    source:
      helm:
        values: |
          "account": "112172658395"
          "clusterName": "Terraform"
          "region": "eu-west-1"
          "repoUrl": "https://github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions.git"
      path: functions/charts/openfaas-functions/
      repoURL: https://github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2023-05-01T19:11:51Z"
    message: 'one or more objects failed to apply, reason: Service "demo-function"
      is invalid: spec.ports[0].name: Required value (retried 10 times).'
    operation:
      initiatedBy:
        automated: true
      retry:
        backoff:
          duration: 10s
          factor: 2
          maxDuration: 3m
        limit: 10
      sync:
        prune: true
        revision: 0e389d2b5fcfe70647ae9a0c51e24a40e62bcb8a
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - RespectIgnoreDifferences=true
    phase: Failed
    retryCount: 10
    startedAt: "2023-05-01T18:48:50Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/write-user unchanged
        name: write-user
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/authenticate-user unchanged
        name: authenticate-user
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/make-passw unchanged
        name: make-passw
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/send-email unchanged
        name: send-email
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/get-translation unchanged
        name: get-translation
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Failed
        kind: Service
        message: 'Service "demo-function" is invalid: spec.ports[0].name: Required
          value'
        name: demo-function
        namespace: openfaas-fn-test
        status: SyncFailed
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/make-passw unchanged
        name: make-passw
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/send-email unchanged
        name: send-email
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/authenticate-user unchanged
        name: authenticate-user
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/demo-function unchanged
        name: demo-function
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/get-translation unchanged
        name: get-translation
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/write-user unchanged
        name: write-user
        namespace: openfaas-fn-test
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 0e389d2b5fcfe70647ae9a0c51e24a40e62bcb8a
      source:
        helm:
          values: |
            "account": "112172658395"
            "clusterName": "Terraform"
            "region": "eu-west-1"
            "repoUrl": "https://github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions.git"
        path: functions/charts/openfaas-functions/
        repoURL: https://github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions.git
        targetRevision: HEAD
  reconciledAt: "2023-05-01T19:42:48Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: authenticate-user
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: demo-function
    namespace: openfaas-fn-test
    status: OutOfSync
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: get-translation
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: make-passw
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: send-email
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: write-user
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: authenticate-user
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: demo-function
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: get-translation
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: make-passw
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: send-email
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: write-user
    namespace: openfaas-fn-test
    status: Synced
    version: v1
  sourceType: Helm
  summary:
    images:
    - 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:authenticate-user-v2
    - 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:demo-function
    - 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:get-translation-v1
    - 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:make-passw-v1
    - 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:send-email-v4
    - 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:write-user-v3
  sync:
    comparedTo:
      destination:
        server: https://kubernetes.default.svc
      source:
        helm:
          values: |
            "account": "112172658395"
            "clusterName": "Terraform"
            "region": "eu-west-1"
            "repoUrl": "https://github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions.git"
        path: functions/charts/openfaas-functions/
        repoURL: https://github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions.git
        targetRevision: HEAD
    revision: 0e389d2b5fcfe70647ae9a0c51e24a40e62bcb8a
    status: OutOfSync
