apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-function
  namespace: openfaas-fn-test
  labels:
    app: demo-function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-function
  template:
    metadata:
      labels:
        app: demo-function
    spec:
      containers:
      - name: demo-function
        image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:demo-function-v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-function
  namespace: openfaas-fn-test

spec:
  selector:
    app: demo-function
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP


