apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-translation
  namespace: openfaas-fn-test
  labels:
    app: get-translation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-translation
  template:
    metadata:
      labels:
        app: get-translation
    spec:
      containers:
      - name: get-translation
        image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:get-translation-v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: get-translation
  namespace: openfaas-fn-test

spec:
  selector:
    app: get-translation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
