apiVersion: apps/v1
kind: Deployment
metadata:
  name: make-passw
  namespace: openfaas-fn
  labels:
    app: make-passw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: make-passw
  template:
    metadata:
      labels:
        app: make-passw
    spec:
      containers:
      - name: make-passw
        image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:make-passw-v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: make-passw
  namespace: openfaas-fn
spec:
  selector:
    app: make-passw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP