apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-email
  namespace: openfaas-fn
  labels:
    app: send-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-email
  template:
    metadata:
      labels:
        app: send-email
    spec:
      containers:
      - name: send-email
        image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:send-email-v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: send-email
  namespace: openfaas-fn
spec:
  selector:
    app: send-email
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP