apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-demo
  namespace: openfaas-fn-test
  labels:
    app: test-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-demo
  template:
    metadata:
      labels:
        app: test-demo
    spec:
      containers:
      - name: test-demo
        image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:test-demo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-demo
  namespace: openfaas-fn-test

spec:
  selector:
    app: test-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
