apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-user
  namespace: openfaas-fn-test
  labels:
    app: write-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: write-user
  template:
    metadata:
      labels:
        app: write-user
    spec:
      containers:
      - name: write-user
        image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:write-user
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: write-user
  namespace: openfaas-fn-test
spec:
  selector:
    app: write-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP