apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-post
  namespace: openfaas-fn
  labels:
    app: write-post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: write-post
  template:
    metadata:
      labels:
        app: write-post
    spec:
      containers:
      - name: write-post
        image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:write-post-v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: write-post
  namespace: openfaas-fn

spec:
  selector:
    app: write-post
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
