gateway: a3c846d513571471da8da03057441b5b-920512917.eu-west-1.elb.amazonaws.com:8080
functions:
  get-translation:
    lang: python
    handler: ./get-translation
    image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:get-translation
  make-passw:
    lang: golang-middleware
    handler: ./make-passw
    image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:password
  write-user:
    lang: python
    secrets: 
      - aws-credentials
    handler: ./write-user
    image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:write-user
  send-email:
    lang: golang-middleware
    handler: ./send-email
    image: 112172658395.dkr.ecr.eu-west-1.amazonaws.com/faas-function-repository:send-email
