name: Deploy to ECR

on:
  push:
    branches:
      - Svanfríður

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  PATH: $PATH:/usr/local/bin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install faas-cli
        run: |
          curl -sSL https://cli.openfaas.com | sudo sh

      - name: Build and push OpenFaaS functions
        id: build-and-push
        run: |
          for function in $(ls functions/*.yml); do
            fn_name=$(basename "$function" .yml)
            echo "Building function $fn_name..."
            faas-cli build -f "$function" --shrinkwrap
            faas-cli push -f "$function"
          done
