name: Tests

on:
  push:
    branchers:
      - Telma

jobs:
  golang_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
      - name: Initialize module for make-passw package
        run: cd functions/make-passw && go mod init github.com/Svanfridurjulia/Exploration-of-Kubernetes-based-FaaS-solutions/functions/make-passw
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
  python_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: pytest
  test_ui:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Move to right folder
        run: cd React_frontend/web_app/
      - name: Install dependencies
        run: npm ci
      - name: Download deps
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm test