name: Tests

on:
  push:
    branches:
      - main

jobs:
  golang_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: cd functions/make-passw && go get .
      - name: Build
        run: cd functions/make-passw && go build -v ./...
      - name: Test with the Go CLI
        run: cd functions/make-passw && go test
  python_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: pytest
  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: react_frontend/web_app/
        run: npm ci
      - name: Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: react_frontend/web_app/
      - name: Run tests
        working-directory: react_frontend/web_app/
        env:
          CI: false
        run: npm test